INSERT INTO estatetype (id, estatetype) VALUES (1, 'Mieszkanie');
INSERT INTO estatetype (id, estatetype) VALUES (2, 'Dom');
INSERT INTO estatetype (id, estatetype) VALUES (3, 'Dzialka');
INSERT INTO role (id, role) VALUES (3, 'Administrator');
INSERT INTO role (id, role) VALUES (2, 'Uzytkownik');
INSERT INTO status (id, status) VALUES (1, 'Zarchiwizowana');
INSERT INTO status (id, status) VALUES (2, 'Aktywna');
INSERT INTO transactiontype (id, transactiontype) VALUES (1, 'Wynajem');
INSERT INTO transactiontype (id, transactiontype) VALUES (2, 'Sprzedaz');